"""update profile

Revision ID: 38acf2907a50
Revises: 21ae86108906
Create Date: 2023-11-07 21:30:50.511528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38acf2907a50"
down_revision: Union[str, None] = "21ae86108906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("first_name", sa.String(length=32), nullable=False)
    )
    op.add_column(
        "profiles", sa.Column("last_name", sa.String(length=32), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "last_name")
    op.drop_column("profiles", "first_name")
    # ### end Alembic commands ###
